/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/contracts": {
    /** Get Analyzed Contract */
    get: operations["get_analyzed_contract_api_v1_contracts_get"];
    /** Analyze */
    post: operations["analyze_api_v1_contracts_post"];
  };
  "/api/v1/events": {
    /** Get Events */
    get: operations["get_events_api_v1_events_get"];
  };
  "/api/v1/stats": {
    /** Get Stats */
    get: operations["get_stats_api_v1_stats_get"];
  };
  "/api/v1/functions": {
    /** List Functions */
    get: operations["list_functions_api_v1_functions_get"];
    /** Create Function */
    post: operations["create_function_api_v1_functions_post"];
  };
  "/api/v1/functions/{id}": {
    /** Get Function Metadata */
    get: operations["get_function_metadata_api_v1_functions__id__get"];
    /** Delete Function */
    delete: operations["delete_function_api_v1_functions__id__delete"];
    /**
     * Update Function
     * @description Update function metadata, empty values wont be updated
     */
    patch: operations["update_function_api_v1_functions__id__patch"];
  };
  "/api/v1/functions/{id}/code": {
    /** Get Function Code */
    get: operations["get_function_code_api_v1_functions__id__code_get"];
  };
  "/api/v1/functions/{id}/test-run": {
    /** Invoke Function */
    post: operations["invoke_function_api_v1_functions__id__test_run_post"];
  };
  "/api/v1/functions/replay_blocks": {
    /** Replay Blocks */
    post: operations["replay_blocks_api_v1_functions_replay_blocks_post"];
  };
  "/api/v1/functions/{id}/stats": {
    /** Get Function Stats */
    get: operations["get_function_stats_api_v1_functions__id__stats_get"];
  };
  "/api/v1/data/nft/": {
    /** Get Nft For Owner */
    get: operations["get_nft_for_owner_api_v1_data_nft__get"];
  };
  "/api/v1/playground/run": {
    /** Run Playground */
    post: operations["run_playground_api_v1_playground_run_post"];
  };
  "/api/v1/samples/{chain_id}-{trigger_type}": {
    /** Get Default Sample */
    get: operations["get_default_sample_api_v1_samples__chain_id___trigger_type__get"];
  };
  "/api/v1/samples": {
    /** Get Sample */
    post: operations["get_sample_api_v1_samples_post"];
  };
  "/public/{id}": {
    /** Get Public Share */
    get: operations["get_public_share_public__id__get"];
    /** Public Shares Options Handler */
    options: operations["public_shares_options_handler_public__id__options"];
  };
  "/api/v1/rpc_api_keys": {
    /** List Rpc Api Keys */
    get: operations["list_rpc_api_keys_api_v1_rpc_api_keys_get"];
  };
  "/api/v1/rpc_api_keys/{id}": {
    /** Get Rpc Api Key */
    get: operations["get_rpc_api_key_api_v1_rpc_api_keys__id__get"];
  };
  "/api/v1/storage/shares": {
    /** List Tenant Public Shares */
    get: operations["list_tenant_public_shares_api_v1_storage_shares_get"];
  };
  "/api/v1/storage/namespaces/{namespace_id}/shares": {
    /** List Namespace Public Shares */
    get: operations["list_namespace_public_shares_api_v1_storage_namespaces__namespace_id__shares_get"];
    /** Create Public Share */
    post: operations["create_public_share_api_v1_storage_namespaces__namespace_id__shares_post"];
  };
  "/api/v1/storage/namespaces/{namespace_id}/shares/{id}": {
    /** Get Public Share */
    get: operations["get_public_share_api_v1_storage_namespaces__namespace_id__shares__id__get"];
    /** Delete Public Share */
    delete: operations["delete_public_share_api_v1_storage_namespaces__namespace_id__shares__id__delete"];
  };
  "/api/v1/storage/namespaces": {
    /** List Tenant Namespaces */
    get: operations["list_tenant_namespaces_api_v1_storage_namespaces_get"];
  };
  "/api/v1/storage/namespaces/{namespace_id}/values": {
    /** Get Namespace Storage */
    get: operations["get_namespace_storage_api_v1_storage_namespaces__namespace_id__values_get"];
    /** Delete Namespace Storage */
    delete: operations["delete_namespace_storage_api_v1_storage_namespaces__namespace_id__values_delete"];
  };
  "/api/v1/storage/namespaces/{namespace_id}/values/{key}": {
    /** Get Key From Namespace Storage */
    get: operations["get_key_from_namespace_storage_api_v1_storage_namespaces__namespace_id__values__key__get"];
    /** Save Key In Namespace Storage */
    post: operations["save_key_in_namespace_storage_api_v1_storage_namespaces__namespace_id__values__key__post"];
    /** Delete Key From Namespace Storage */
    delete: operations["delete_key_from_namespace_storage_api_v1_storage_namespaces__namespace_id__values__key__delete"];
  };
  "/api/v1/webhooks": {
    /** List Webhooks */
    get: operations["list_webhooks_api_v1_webhooks_get"];
    /** Create Webhook */
    post: operations["create_webhook_api_v1_webhooks_post"];
  };
  "/api/v1/webhooks/{id}": {
    /** Get Webhook */
    get: operations["get_webhook_api_v1_webhooks__id__get"];
    /** Delete Webhook */
    delete: operations["delete_webhook_api_v1_webhooks__id__delete"];
  };
  "/api/v1/notifications/templates": {
    /** Get Templates */
    get: operations["get_templates_api_v1_notifications_templates_get"];
    /** Create Template */
    post: operations["create_template_api_v1_notifications_templates_post"];
  };
  "/api/v1/notifications/templates/{template_id}": {
    /** Get Template */
    get: operations["get_template_api_v1_notifications_templates__template_id__get"];
    /** Delete Template */
    delete: operations["delete_template_api_v1_notifications_templates__template_id__delete"];
  };
  "/api/v1/notifications/users/{id}": {
    /** Delete User */
    delete: operations["delete_user_api_v1_notifications_users__id__delete"];
  };
  "/api/v1/notifications/users": {
    /** List Users */
    get: operations["list_users_api_v1_notifications_users_get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** Address Trigger */
    AddressTriggerData: {
      /**
       * Type
       * @enum {string}
       */
      type: "TRIGGER_TYPE_ADDRESS";
      /**
       * Address
       * @description Address to set trigger on
       * @example 0x283af0b28c62c092c9727f1ee09c02ca627eb7f5
       */
      address: string;
      /**
       * Locations
       * @description Locations to set trigger on. Leave empty to set trigger on all locations.
       * @example [
       *   "trace_to",
       *   "trace_from"
       * ]
       */
      locations?: components["schemas"]["PydanticAddressLocations"][];
      /**
       * Custom parameters
       * @description Parameters to be passed to the function when it is triggered by this trigger
       * @example {
       *   "key": "value",
       *   "key2": "value2"
       * }
       */
      custom_parameters?: {
        [key: string]: string;
      };
    };
    /** ContractRequest */
    ContractRequest: {
      /**
       * Chain
       * @description Chain for the function to run on
       * @default CHAIN_ETH_MAINNET
       * @example CHAIN_ETH_MAINNET
       * @enum {string}
       */
      chain_id?: "CHAIN_ETH_MAINNET" | "CHAIN_ETH_SEPOLIA" | "CHAIN_ARBITRUM_ONE" | "CHAIN_POLYGON_MAINNET" | "CHAIN_BNB_MAINNET" | "CHAIN_BNB_TESTNET";
      /**
       * Contract Address
       * @description EVM address of the contract
       * @example 0x283af0b28c62c092c9727f1ee09c02ca627eb7f5
       */
      contract_address: string;
    };
    /** CreateTemplateRequest */
    CreateTemplateRequest: {
      /**
       * Function Id
       * @description The id for an existing function, that implements the template logic
       * @example 12345678-1234-1234-1234-123456789abc
       */
      function_id: string;
      /**
       * Parameter Names
       * @description List of Parameters needed for creating a notification instance from this template
       * @example [
       *   "address",
       *   "threshold"
       * ]
       */
      parameter_names?: string[];
      /**
       * Trigger
       * @description A user trigger that will be set for every notification instance created from this template. Note that the trigger can contain parameter placeholder. ie $$address$$
       */
      user_trigger: components["schemas"]["AddressTriggerData"] | components["schemas"]["EventTriggerData"] | components["schemas"]["FunctionTriggerData"] | components["schemas"]["NewBlockTriggerData"] | components["schemas"]["NewContractTriggerData"] | components["schemas"]["StorageTriggerData"];
    };
    /** Event */
    Event: {
      /**
       * Event type
       * @description The type of the system event that occurred
       * @example EVENT_TYPE_RUN_FUNCTION
       * @enum {string}
       */
      event_type: "EVENT_TYPE_UNSPECIFIED" | "EVENT_TYPE_RUN_FUNCTION" | "EVENT_TYPE_WEBHOOK_RESPONSE" | "EVENT_TYPE_FUNCTION_RATE_LIMIT_EXCEEDED" | "EVENT_TYPE_DATA_SEND_QUOTA_EXCEEDED";
      /** Timestamp */
      timestamp?: string;
      /** Payload */
      payload?: string;
    };
    /** Event Trigger */
    EventTriggerData: {
      /**
       * Type
       * @enum {string}
       */
      type: "TRIGGER_TYPE_EVENT";
      /**
       * Event
       * @description Event signature to set trigger on
       * @example 0x04fb42f6b9d37e87d9febc9946d24a6135f9d2435fd0e163eeb1e025817605b2
       */
      event: string;
      /**
       * Custom parameters
       * @description Parameters to be passed to the function when it is triggered by this trigger
       * @example {
       *   "key": "value",
       *   "key2": "value2"
       * }
       */
      custom_parameters?: {
        [key: string]: string;
      };
    };
    /** ExecuteFunctionArgs */
    ExecuteFunctionArgs: {
      /** Context */
      context: Record<string, never>;
      /** Data */
      data: Record<string, never>;
    };
    /** FuncInfo */
    FuncInfo: {
      /** Chain Id */
      chain_id: string;
      /** Function Id */
      function_id: string;
      /** Triggers */
      triggers: (components["schemas"]["AddressTriggerData"] | components["schemas"]["EventTriggerData"] | components["schemas"]["FunctionTriggerData"] | components["schemas"]["NewBlockTriggerData"] | components["schemas"]["NewContractTriggerData"] | components["schemas"]["StorageTriggerData"])[];
      /** Webhook Id */
      webhook_id: string;
      /** Function Name */
      function_name: string;
      /** Is Enabled */
      is_enabled: boolean;
      /** Should Send Std Streams */
      should_send_std_streams: boolean;
      /** Function Code */
      function_code: string;
      /** Function Code File Listing */
      function_code_file_listing?: Record<string, never>[];
    };
    /** FuncInfoPatch */
    FuncInfoPatch: {
      /**
       * Function name
       * @description A descriptive function name
       * @example my_function
       */
      function_name?: string;
      /**
       * Is function enabled
       * @description Whether the function will be triggered or not
       * @example true
       */
      is_enabled?: boolean;
      /**
       * Webhook ID
       * @description Webhook ID as returned from SaveWebhook
       * @example 12345678-1234-1234-1234-123456789abc
       */
      webhook_id?: string;
      /**
       * Function code
       * @description Your function code (or zip file containing a main.ts / main.js entry point) encoded in base 64
       * @example ZXhwb3J0IGFzeW5jIGZ1bmN0aW9uIHRyaWdnZXJIYW5kbGVyKGNvbnRleHQsIGRhdGEpIHsKICAgIHJldHVybiB7ImNvbnRleHQiOiBjb250ZXh0LCAiZGF0YSI6ZGF0YX07Cn0=
       */
      function_code?: string;
      /**
       * Should send stdout and stderr to webhook
       * @description Whether the result of the function stdout and stderr will be sent to the webhook in addition to the result of the function
       * @example true
       */
      should_send_std_streams?: boolean;
      /**
       * Triggers
       * @description Change the triggers that will invoke the function.
       */
      triggers?: (components["schemas"]["AddressTriggerData"] | components["schemas"]["EventTriggerData"] | components["schemas"]["FunctionTriggerData"] | components["schemas"]["NewBlockTriggerData"] | components["schemas"]["NewContractTriggerData"] | components["schemas"]["StorageTriggerData"])[];
    };
    /** Function Trigger */
    FunctionTriggerData: {
      /**
       * Type
       * @enum {string}
       */
      type: "TRIGGER_TYPE_FUNCTION";
      /**
       * Function
       * @description Function signature to set trigger on
       * @example 0xbeabacc8
       */
      function: string;
      /**
       * Custom parameters
       * @description Parameters to be passed to the function when it is triggered by this trigger
       * @example {
       *   "key": "value",
       *   "key2": "value2"
       * }
       */
      custom_parameters?: {
        [key: string]: string;
      };
    };
    /** GetSampleRequest */
    GetSampleRequest: {
      /**
       * Chain
       * @description Chain for the function to run on
       * @default CHAIN_ETH_MAINNET
       * @example CHAIN_ETH_MAINNET
       * @enum {string}
       */
      chain_id?: "CHAIN_ETH_MAINNET" | "CHAIN_ETH_SEPOLIA" | "CHAIN_ARBITRUM_ONE" | "CHAIN_POLYGON_MAINNET" | "CHAIN_STARKNET_MAINNET" | "CHAIN_COSMOS_OSMOSIS" | "CHAIN_BNB_MAINNET" | "CHAIN_BNB_TESTNET" | "CHAIN_MANTLE_MAINNET" | "CHAIN_SOLANA_MAINNET" | "CHAIN_FANTOM_MAINNET" | "CHAIN_BASE_MAINNET";
      /**
       * Trigger
       * @description Trigger that will invoke the function
       */
      trigger: components["schemas"]["AddressTriggerData"] | components["schemas"]["EventTriggerData"] | components["schemas"]["FunctionTriggerData"] | components["schemas"]["NewBlockTriggerData"] | components["schemas"]["NewContractTriggerData"] | components["schemas"]["StorageTriggerData"];
      /**
       * Block number
       * @description Block number to samples trigger from
       * @example 123456
       */
      block_number: number;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** New Block Trigger */
    NewBlockTriggerData: {
      /**
       * Type
       * @enum {string}
       */
      type: "TRIGGER_TYPE_NEW_BLOCK";
      /**
       * Custom parameters
       * @description Parameters to be passed to the function when it is triggered by this trigger
       * @example {
       *   "key": "value",
       *   "key2": "value2"
       * }
       */
      custom_parameters?: {
        [key: string]: string;
      };
    };
    /** New Contract Trigger */
    NewContractTriggerData: {
      /**
       * Type
       * @enum {string}
       */
      type: "TRIGGER_TYPE_NEW_CONTRACT";
      /**
       * Custom parameters
       * @description Parameters to be passed to the function when it is triggered by this trigger
       * @example {
       *   "key": "value",
       *   "key2": "value2"
       * }
       */
      custom_parameters?: {
        [key: string]: string;
      };
    };
    /** Page[Event] */
    Page_Event_: {
      /** Items */
      items: components["schemas"]["Event"][];
      /** Total */
      total?: number;
      /** Page */
      page?: number;
      /** Size */
      size?: number;
      /** Pages */
      pages?: number;
    };
    /** Page[FuncInfo] */
    Page_FuncInfo_: {
      /** Items */
      items: components["schemas"]["FuncInfo"][];
      /** Total */
      total?: number;
      /** Page */
      page?: number;
      /** Size */
      size?: number;
      /** Pages */
      pages?: number;
    };
    /** Page[PublicShareInfo] */
    Page_PublicShareInfo_: {
      /** Items */
      items: components["schemas"]["PublicShareInfo"][];
      /** Total */
      total?: number;
      /** Page */
      page?: number;
      /** Size */
      size?: number;
      /** Pages */
      pages?: number;
    };
    /** Page[RpcApiKeyId] */
    Page_RpcApiKeyId_: {
      /** Items */
      items: components["schemas"]["RpcApiKeyId"][];
      /** Total */
      total?: number;
      /** Page */
      page?: number;
      /** Size */
      size?: number;
      /** Pages */
      pages?: number;
    };
    /** Page[Stat] */
    Page_Stat_: {
      /** Items */
      items: components["schemas"]["Stat"][];
      /** Total */
      total?: number;
      /** Page */
      page?: number;
      /** Size */
      size?: number;
      /** Pages */
      pages?: number;
    };
    /** Page[VariableStorageMapping] */
    Page_VariableStorageMapping_: {
      /** Items */
      items: components["schemas"]["VariableStorageMapping"][];
      /** Total */
      total?: number;
      /** Page */
      page?: number;
      /** Size */
      size?: number;
      /** Pages */
      pages?: number;
    };
    /** Page[WebhookInfo] */
    Page_WebhookInfo_: {
      /** Items */
      items: components["schemas"]["WebhookInfo"][];
      /** Total */
      total?: number;
      /** Page */
      page?: number;
      /** Size */
      size?: number;
      /** Pages */
      pages?: number;
    };
    /** PlaygroundFunctionData */
    PlaygroundFunctionData: {
      /** Code */
      code: string;
      /** Context */
      context: Record<string, never>;
      /** Data */
      data: Record<string, never>;
      /** Sendstdstreams */
      sendStdStreams: boolean;
    };
    /** PublicShareInfo */
    PublicShareInfo: {
      /** Public Share Id */
      public_share_id: string;
      /** Namespace Id */
      namespace_id: string;
      /** Description */
      description: string;
      /** Enabled */
      enabled: boolean;
      /** Url */
      url?: string;
    };
    /**
     * PydanticAddressLocations
     * @description An enumeration.
     * @enum {unknown}
     */
    PydanticAddressLocations: "trace_to" | "trace_from" | "trace_input" | "trace_output" | "log_emitter" | "log_topic" | "log_data" | "storage_key" | "storage_value" | "storage_address" | "event_attribute";
    /** ReplayBlocksParams */
    ReplayBlocksParams: {
      /**
       * Functions
       * @description List of function IDs to replay
       */
      functions: string[];
      /**
       * Chain
       * @description The chain from which blocks will be replayed
       * @default CHAIN_ETH_MAINNET
       * @example CHAIN_ETH_MAINNET
       * @enum {string}
       */
      chain_id?: "CHAIN_ETH_MAINNET" | "CHAIN_ETH_SEPOLIA" | "CHAIN_ARBITRUM_ONE" | "CHAIN_POLYGON_MAINNET" | "CHAIN_STARKNET_MAINNET" | "CHAIN_COSMOS_OSMOSIS" | "CHAIN_BNB_MAINNET" | "CHAIN_BNB_TESTNET" | "CHAIN_MANTLE_MAINNET" | "CHAIN_SOLANA_MAINNET" | "CHAIN_FANTOM_MAINNET" | "CHAIN_BASE_MAINNET";
      /**
       * StartBlockNumber
       * @description The first block number that will be replayed
       */
      start_block_number: number;
      /**
       * EndBlockNumber
       * @description The last block number that will be replayed
       */
      end_block_number: number;
      /**
       * XLFlag
       * @description If true, invokes extended replay. This is used when replaying a large number of blocks
       * @default false
       */
      xl_flag?: boolean;
    };
    /** RpcApiKeyId */
    RpcApiKeyId: {
      /** Api Key Id */
      api_key_id: string;
    };
    /** RpcApiKeyInfo */
    RpcApiKeyInfo: {
      /** Api Key Id */
      api_key_id: string;
      /** Description */
      description: string;
      /** Api Key Value */
      api_key_value: string;
      /** Usages */
      usages: components["schemas"]["Usage"][];
      /** Usage Start Date */
      usage_start_date: string;
      /** Usage End Date */
      usage_end_date: string;
    };
    /** SaveFunctionRequest */
    SaveFunctionRequest: {
      /**
       * Chain
       * @description Chain for the function to run on
       * @default CHAIN_ETH_MAINNET
       * @example CHAIN_ETH_MAINNET
       * @enum {string}
       */
      chain_id?: "CHAIN_ETH_MAINNET" | "CHAIN_ETH_SEPOLIA" | "CHAIN_ARBITRUM_ONE" | "CHAIN_POLYGON_MAINNET" | "CHAIN_STARKNET_MAINNET" | "CHAIN_COSMOS_OSMOSIS" | "CHAIN_BNB_MAINNET" | "CHAIN_BNB_TESTNET" | "CHAIN_MANTLE_MAINNET" | "CHAIN_SOLANA_MAINNET" | "CHAIN_FANTOM_MAINNET" | "CHAIN_BASE_MAINNET";
      /**
       * Triggers
       * @description Triggers that will invoke the function
       */
      triggers: (components["schemas"]["AddressTriggerData"] | components["schemas"]["EventTriggerData"] | components["schemas"]["FunctionTriggerData"] | components["schemas"]["NewBlockTriggerData"] | components["schemas"]["NewContractTriggerData"] | components["schemas"]["StorageTriggerData"])[];
      /**
       * Webhook ID
       * @description Webhook ID as returned from SaveWebhook
       * @example 12345678-1234-1234-1234-123456789abc
       */
      webhook_id: string;
      /**
       * Function name
       * @description A name to identify the function, must be unique per tenant
       * @example my_function
       */
      function_name: string;
      /**
       * Function code
       * @description Your function code encoded in base 64
       * @example ZXhwb3J0IGFzeW5jIGZ1bmN0aW9uIHRyaWdnZXJIYW5kbGVyKGNvbnRleHQsIGRhdGEpIHsKICAgIHJldHVybiB7ImNvbnRleHQiOiBjb250ZXh0LCAiZGF0YSI6ZGF0YX07Cn0=
       */
      function_code: string;
      /**
       * Should send stdout and stderr to webhook
       * @description Whether the result of the function stdout and stderr will be sent to the webhook in addition to the result of the function
       * @default true
       * @example true
       */
      should_send_std_streams?: boolean;
    };
    /** SaveFunctionResponse */
    SaveFunctionResponse: {
      /** Function Id */
      function_id?: string;
    };
    /** SavePublicShareRequest */
    SavePublicShareRequest: {
      /**
       * Description
       * @description A description of the public share
       * @example This is a public share
       */
      description: string;
      /**
       * Enabled
       * @description Whether the public share is enabled
       * @example true
       */
      enabled: boolean;
    };
    /** SavePublicShareResponse */
    SavePublicShareResponse: {
      /** Public Share Id */
      public_share_id?: string;
    };
    /** SaveWebhookRequest */
    SaveWebhookRequest: {
      /**
       * Webhook URL
       * @description A URL to post output of a function
       * @example https://example.com/webhook
       */
      url: string;
      /**
       * Webhook secret
       * @description A secret to pass in Authorization header when posting
       * @example secret
       */
      secret: string;
      /**
       * Webhook name
       * @description A name to identify the webhook, must be unique per tenant
       * @example webhook_name
       */
      webhook_name: string;
    };
    /** SaveWebhookResponse */
    SaveWebhookResponse: {
      /** Webhook Id */
      webhook_id?: string;
    };
    /** SbUserInfo */
    SbUserInfo: {
      /** Sb User Id */
      sb_user_id: string;
      /** Wallet Address */
      wallet_address: string;
    };
    /** Stat */
    Stat: {
      /** Tenant Id */
      tenant_id?: string;
      /** Start Time */
      start_time?: string;
      /** End Time */
      end_time?: string;
      /**
       * Interval
       * @description The time interval for the stats
       * @example STAT_INTERVAL_HOUR
       * @enum {string}
       */
      interval: "STAT_INTERVAL_UNSPECIFIED" | "STAT_INTERVAL_HOUR" | "STAT_INTERVAL_DAY" | "STAT_INTERVAL_WEEK" | "STAT_INTERVAL_MONTH";
      /**
       * Event type
       * @description The type of the system event that occurred
       * @example EVENT_TYPE_RUN_FUNCTION
       * @enum {string}
       */
      event_type: "EVENT_TYPE_UNSPECIFIED" | "EVENT_TYPE_RUN_FUNCTION" | "EVENT_TYPE_WEBHOOK_RESPONSE" | "EVENT_TYPE_FUNCTION_RATE_LIMIT_EXCEEDED" | "EVENT_TYPE_DATA_SEND_QUOTA_EXCEEDED";
      /** Func Id */
      func_id?: string;
      /** Webhook Id */
      webhook_id?: string;
      /** Stats */
      stats?: string;
    };
    /** By Slot */
    StorageSlotTrigger: {
      /**
       * Slot
       * @description Hex encoded slot value
       * @example 0x4567
       */
      variable_slot: string;
    };
    /** Storage Trigger */
    StorageTriggerData: {
      /**
       * Type
       * @enum {string}
       */
      type: "TRIGGER_TYPE_STORAGE_ACCESS";
      /**
       * Storage Address
       * @description Address to watch for storage changes
       * @example 0x4db1f25d3d98600140dfc18deb7515be5bd293af
       */
      storage_address: string;
      /**
       * Follow Proxy
       * @description Should we search for a variable name in an implementation contract
       * @default true
       */
      follow_proxy?: boolean;
      /** Variable */
      variable: components["schemas"]["StorageVariableTrigger"] | components["schemas"]["StorageSlotTrigger"];
      /**
       * Custom parameters
       * @description Parameters to be passed to the function when it is triggered by this trigger
       * @example {
       *   "key": "value",
       *   "key2": "value2"
       * }
       */
      custom_parameters?: {
        [key: string]: string;
      };
    };
    /** By Variable Name */
    StorageVariableTrigger: {
      /**
       * Variable Name
       * @description Name of variable to watch for changes
       * @example totalSupply
       */
      variable_name: string;
    };
    /** TemplateInfo */
    TemplateInfo: {
      /** Template Id */
      template_id: string;
      /** Tenant Id */
      tenant_id: string;
      /** Function Id */
      function_id: string;
      /** User Trigger */
      user_trigger: components["schemas"]["AddressTriggerData"] | components["schemas"]["EventTriggerData"] | components["schemas"]["FunctionTriggerData"] | components["schemas"]["NewBlockTriggerData"] | components["schemas"]["NewContractTriggerData"] | components["schemas"]["StorageTriggerData"];
      /** Parameter Names */
      parameter_names: string[];
    };
    /** Usage */
    Usage: {
      /** Usage Plan Name */
      usage_plan_name: string;
      /** Period */
      period: string;
      /** Quota */
      quota: number;
      /** Usage Entries */
      usage_entries: components["schemas"]["UsageEntry"][];
    };
    /** UsageEntry */
    UsageEntry: {
      /** Used */
      used: number;
      /** Remaining */
      remaining: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** VariableStorageMapping */
    VariableStorageMapping: {
      /** Name */
      name?: string;
      /** First Slot */
      first_slot?: string;
      /** Last Slot */
      last_slot?: string;
    };
    /** WebhookInfo */
    WebhookInfo: {
      /** Url */
      url: string;
      /** Secret */
      secret: string;
      /** Webhook Id */
      webhook_id: string;
      /** Webhook Name */
      webhook_name: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Get Analyzed Contract */
  get_analyzed_contract_api_v1_contracts_get: {
    parameters: {
      query: {
        /**
         * @description Chain for the function to run on
         * @example CHAIN_ETH_MAINNET
         */
        chain_id?: "CHAIN_ETH_MAINNET" | "CHAIN_ETH_SEPOLIA" | "CHAIN_ARBITRUM_ONE" | "CHAIN_POLYGON_MAINNET" | "CHAIN_BNB_MAINNET" | "CHAIN_BNB_TESTNET";
        /**
         * @description EVM address of the contract
         * @example 0x283af0b28c62c092c9727f1ee09c02ca627eb7f5
         */
        contract_address: string;
        /** @description Should we fetch the analyzed implementation contract */
        follow_proxy?: boolean;
        page?: number;
        size?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Page_VariableStorageMapping_"];
        };
      };
      /** @description Bad Request */
      400: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: never;
      };
    };
  };
  /** Analyze */
  analyze_api_v1_contracts_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ContractRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Bad Request */
      400: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: never;
      };
    };
  };
  /** Get Events */
  get_events_api_v1_events_get: {
    parameters: {
      query?: {
        func_id?: string;
        status_filter?: string;
        type_filter?: string;
        page?: number;
        size?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Page_Event_"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: never;
      };
    };
  };
  /** Get Stats */
  get_stats_api_v1_stats_get: {
    parameters: {
      query?: {
        start_time?: string;
        end_time?: string;
        type_filter?: string;
        function_id?: string;
        webhook_id?: string;
        page?: number;
        size?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Page_Stat_"];
        };
      };
      /** @description Statistics not found */
      404: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: never;
      };
    };
  };
  /** List Functions */
  list_functions_api_v1_functions_get: {
    parameters: {
      query?: {
        page?: number;
        size?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Page_FuncInfo_"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: never;
      };
    };
  };
  /** Create Function */
  create_function_api_v1_functions_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SaveFunctionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["SaveFunctionResponse"];
        };
      };
      /** @description Bad Request */
      400: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: never;
      };
    };
  };
  /** Get Function Metadata */
  get_function_metadata_api_v1_functions__id__get: {
    parameters: {
      query?: {
        include_function_code?: boolean;
      };
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["FuncInfo"];
        };
      };
      /** @description Function not found */
      404: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: never;
      };
    };
  };
  /** Delete Function */
  delete_function_api_v1_functions__id__delete: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["FuncInfo"];
        };
      };
      /** @description Function not found */
      404: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: never;
      };
    };
  };
  /**
   * Update Function
   * @description Update function metadata, empty values wont be updated
   */
  update_function_api_v1_functions__id__patch: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FuncInfoPatch"];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Function not found */
      404: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: never;
      };
    };
  };
  /** Get Function Code */
  get_function_code_api_v1_functions__id__code_get: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Function code or zip file */
      200: {
        content: {
          "application/octet-stream": unknown;
        };
      };
      /** @description Function not found */
      404: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: never;
      };
    };
  };
  /** Invoke Function */
  invoke_function_api_v1_functions__id__test_run_post: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ExecuteFunctionArgs"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: never;
      };
      /** @description Function not found */
      404: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: never;
      };
    };
  };
  /** Replay Blocks */
  replay_blocks_api_v1_functions_replay_blocks_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReplayBlocksParams"];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description invalid input */
      400: {
        content: never;
      };
      /** @description Function not found */
      404: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: never;
      };
    };
  };
  /** Get Function Stats */
  get_function_stats_api_v1_functions__id__stats_get: {
    parameters: {
      query?: {
        start_time?: string;
        end_time?: string;
        type_filter?: string;
        page?: number;
        size?: number;
      };
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Page_Stat_"];
        };
      };
      /** @description Function or its statistics not found */
      404: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: never;
      };
    };
  };
  /** Get Nft For Owner */
  get_nft_for_owner_api_v1_data_nft__get: {
    parameters: {
      query: {
        owner: string;
        /**
         * @description Chain that the address is on
         * @example CHAIN_STARKNET_MAINNET
         */
        chain: "CHAIN_STARKNET_MAINNET";
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Bad arguments */
      400: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: never;
      };
    };
  };
  /** Run Playground */
  run_playground_api_v1_playground_run_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["PlaygroundFunctionData"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Default Sample */
  get_default_sample_api_v1_samples__chain_id___trigger_type__get: {
    parameters: {
      path: {
        chain_id: string;
        trigger_type: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Sample */
  get_sample_api_v1_samples_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["GetSampleRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Public Share */
  get_public_share_public__id__get: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Data not found */
      404: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: never;
      };
    };
  };
  /** Public Shares Options Handler */
  public_shares_options_handler_public__id__options: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Rpc Api Keys */
  list_rpc_api_keys_api_v1_rpc_api_keys_get: {
    parameters: {
      query?: {
        page?: number;
        size?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Page_RpcApiKeyId_"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: never;
      };
    };
  };
  /** Get Rpc Api Key */
  get_rpc_api_key_api_v1_rpc_api_keys__id__get: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RpcApiKeyInfo"];
        };
      };
      /** @description RPC API key not found */
      404: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: never;
      };
    };
  };
  /** List Tenant Public Shares */
  list_tenant_public_shares_api_v1_storage_shares_get: {
    parameters: {
      query?: {
        page?: number;
        size?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Page_PublicShareInfo_"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: never;
      };
    };
  };
  /** List Namespace Public Shares */
  list_namespace_public_shares_api_v1_storage_namespaces__namespace_id__shares_get: {
    parameters: {
      query?: {
        page?: number;
        size?: number;
      };
      path: {
        namespace_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Page_PublicShareInfo_"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: never;
      };
    };
  };
  /** Create Public Share */
  create_public_share_api_v1_storage_namespaces__namespace_id__shares_post: {
    parameters: {
      path: {
        namespace_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SavePublicShareRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SavePublicShareResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: never;
      };
    };
  };
  /** Get Public Share */
  get_public_share_api_v1_storage_namespaces__namespace_id__shares__id__get: {
    parameters: {
      path: {
        namespace_id: string;
        id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PublicShareInfo"];
        };
      };
      /** @description Public share not found */
      404: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: never;
      };
    };
  };
  /** Delete Public Share */
  delete_public_share_api_v1_storage_namespaces__namespace_id__shares__id__delete: {
    parameters: {
      path: {
        namespace_id: string;
        id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PublicShareInfo"];
        };
      };
      /** @description Public share not found */
      404: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: never;
      };
    };
  };
  /** List Tenant Namespaces */
  list_tenant_namespaces_api_v1_storage_namespaces_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": string[];
        };
      };
      /** @description No storage namespaces found */
      404: {
        content: never;
      };
      /** @description Internal Server Error */
      500: {
        content: never;
      };
    };
  };
  /** Get Namespace Storage */
  get_namespace_storage_api_v1_storage_namespaces__namespace_id__values_get: {
    parameters: {
      path: {
        namespace_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Namespace storage not found */
      404: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: never;
      };
    };
  };
  /** Delete Namespace Storage */
  delete_namespace_storage_api_v1_storage_namespaces__namespace_id__values_delete: {
    parameters: {
      path: {
        namespace_id: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Namespace storage not found */
      404: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: never;
      };
    };
  };
  /** Get Key From Namespace Storage */
  get_key_from_namespace_storage_api_v1_storage_namespaces__namespace_id__values__key__get: {
    parameters: {
      path: {
        namespace_id: string;
        key: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Namespace storage not found */
      404: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: never;
      };
    };
  };
  /** Save Key In Namespace Storage */
  save_key_in_namespace_storage_api_v1_storage_namespaces__namespace_id__values__key__post: {
    parameters: {
      path: {
        namespace_id: string;
        key: string;
      };
    };
    requestBody: {
      content: {
        "application/json": string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Namespace storage not found */
      404: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: never;
      };
    };
  };
  /** Delete Key From Namespace Storage */
  delete_key_from_namespace_storage_api_v1_storage_namespaces__namespace_id__values__key__delete: {
    parameters: {
      path: {
        namespace_id: string;
        key: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Namespace storage / key not found */
      404: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: never;
      };
    };
  };
  /** List Webhooks */
  list_webhooks_api_v1_webhooks_get: {
    parameters: {
      query?: {
        page?: number;
        size?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Page_WebhookInfo_"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: never;
      };
    };
  };
  /** Create Webhook */
  create_webhook_api_v1_webhooks_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SaveWebhookRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["SaveWebhookResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: never;
      };
    };
  };
  /** Get Webhook */
  get_webhook_api_v1_webhooks__id__get: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["WebhookInfo"];
        };
      };
      /** @description Webhook not found */
      404: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: never;
      };
    };
  };
  /** Delete Webhook */
  delete_webhook_api_v1_webhooks__id__delete: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["WebhookInfo"];
        };
      };
      /** @description Webhook not found */
      404: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: never;
      };
    };
  };
  /** Get Templates */
  get_templates_api_v1_notifications_templates_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TemplateInfo"][];
        };
      };
    };
  };
  /** Create Template */
  create_template_api_v1_notifications_templates_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateTemplateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": string;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Template */
  get_template_api_v1_notifications_templates__template_id__get: {
    parameters: {
      path: {
        template_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TemplateInfo"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Template */
  delete_template_api_v1_notifications_templates__template_id__delete: {
    parameters: {
      path: {
        template_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete User */
  delete_user_api_v1_notifications_users__id__delete: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Users */
  list_users_api_v1_notifications_users_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SbUserInfo"][];
        };
      };
    };
  };
}
